// 한국 주식 종목 목록 (검색용 로컬 데이터)
// 네이버/Finnhub처럼 한국 종목을 이름으로 검색할 수 있는 공개 API가 따로 없어서,
// 자주 거래되는 KOSPI/KOSDAQ 종목을 직접 목록으로 관리합니다.
// market: 'KOSPI' | 'KOSDAQ' — Yahoo Finance 폴백 조회 시 .KS / .KQ 접미사를 정하는 데 사용됩니다.
// 필요한 종목이 없으면 이 배열에 자유롭게 추가하면 됩니다.

export const KOREAN_STOCKS = [
  { code: '005930', name: '삼성전자', nameEn: 'Samsung Electronics', market: 'KOSPI' },
  { code: '000660', name: 'SK하이닉스', nameEn: 'SK Hynix', market: 'KOSPI' },
  { code: '373220', name: 'LG에너지솔루션', nameEn: 'LG Energy Solution', market: 'KOSPI' },
  { code: '207940', name: '삼성바이오로직스', nameEn: 'Samsung Biologics', market: 'KOSPI' },
  { code: '005380', name: '현대차', nameEn: 'Hyundai Motor', market: 'KOSPI' },
  { code: '000270', name: '기아', nameEn: 'Kia', market: 'KOSPI' },
  { code: '005490', name: 'POSCO홀딩스', nameEn: 'POSCO Holdings', market: 'KOSPI' },
  { code: '051910', name: 'LG화학', nameEn: 'LG Chem', market: 'KOSPI' },
  { code: '006400', name: '삼성SDI', nameEn: 'Samsung SDI', market: 'KOSPI' },
  { code: '035420', name: 'NAVER', nameEn: 'Naver', market: 'KOSPI' },
  { code: '035720', name: '카카오', nameEn: 'Kakao', market: 'KOSPI' },
  { code: '028260', name: '삼성물산', nameEn: 'Samsung C&T', market: 'KOSPI' },
  { code: '012330', name: '현대모비스', nameEn: 'Hyundai Mobis', market: 'KOSPI' },
  { code: '066570', name: 'LG전자', nameEn: 'LG Electronics', market: 'KOSPI' },
  { code: '105560', name: 'KB금융', nameEn: 'KB Financial Group', market: 'KOSPI' },
  { code: '055550', name: '신한지주', nameEn: 'Shinhan Financial Group', market: 'KOSPI' },
  { code: '086790', name: '하나금융지주', nameEn: 'Hana Financial Group', market: 'KOSPI' },
  { code: '316140', name: '우리금융지주', nameEn: 'Woori Financial Group', market: 'KOSPI' },
  { code: '015760', name: '한국전력', nameEn: 'KEPCO', market: 'KOSPI' },
  { code: '032830', name: '삼성생명', nameEn: 'Samsung Life Insurance', market: 'KOSPI' },
  { code: '018260', name: '삼성에스디에스', nameEn: 'Samsung SDS', market: 'KOSPI' },
  { code: '009150', name: '삼성전기', nameEn: 'Samsung Electro-Mechanics', market: 'KOSPI' },
  { code: '010130', name: '고려아연', nameEn: 'Korea Zinc', market: 'KOSPI' },
  { code: '011200', name: 'HMM', nameEn: 'HMM', market: 'KOSPI' },
  { code: '003550', name: 'LG', nameEn: 'LG Corp', market: 'KOSPI' },
  { code: '034730', name: 'SK', nameEn: 'SK Inc', market: 'KOSPI' },
  { code: '096770', name: 'SK이노베이션', nameEn: 'SK Innovation', market: 'KOSPI' },
  { code: '017670', name: 'SK텔레콤', nameEn: 'SK Telecom', market: 'KOSPI' },
  { code: '030200', name: 'KT', nameEn: 'KT Corp', market: 'KOSPI' },
  { code: '036570', name: '엔씨소프트', nameEn: 'NCsoft', market: 'KOSPI' },
  { code: '068270', name: '셀트리온', nameEn: 'Celltrion', market: 'KOSPI' },
  { code: '326030', name: 'SK바이오팜', nameEn: 'SK Biopharm', market: 'KOSPI' },
  { code: '010950', name: 'S-Oil', nameEn: 'S-Oil', market: 'KOSPI' },
  { code: '011170', name: '롯데케미칼', nameEn: 'Lotte Chemical', market: 'KOSPI' },
  { code: '097950', name: 'CJ제일제당', nameEn: 'CJ CheilJedang', market: 'KOSPI' },
  { code: '023530', name: '롯데쇼핑', nameEn: 'Lotte Shopping', market: 'KOSPI' },
  { code: '000810', name: '삼성화재', nameEn: 'Samsung Fire & Marine Insurance', market: 'KOSPI' },
  { code: '024110', name: '기업은행', nameEn: 'IBK', market: 'KOSPI' },
  { code: '047810', name: '한국항공우주', nameEn: 'Korea Aerospace Industries', market: 'KOSPI' },
  { code: '161390', name: '한국타이어앤테크놀로지', nameEn: 'Hankook Tire & Technology', market: 'KOSPI' },
  { code: '251270', name: '넷마블', nameEn: 'Netmarble', market: 'KOSPI' },
  { code: '247540', name: '에코프로비엠', nameEn: 'EcoPro BM', market: 'KOSDAQ' },
  { code: '086520', name: '에코프로', nameEn: 'EcoPro', market: 'KOSDAQ' },
  { code: '263750', name: '펄어비스', nameEn: 'Pearl Abyss', market: 'KOSDAQ' },
  { code: '042700', name: '한미반도체', nameEn: 'Hanmi Semiconductor', market: 'KOSDAQ' },
  { code: '357780', name: '솔브레인', nameEn: 'Soulbrain', market: 'KOSDAQ' },
  { code: '039030', name: '이오테크닉스', nameEn: 'EO Technics', market: 'KOSDAQ' },
  { code: '277810', name: '레인보우로보틱스', nameEn: 'Rainbow Robotics', market: 'KOSDAQ' },
  { code: '058470', name: '리노공업', nameEn: 'Leeno Industrial', market: 'KOSDAQ' },
  { code: '035900', name: 'JYP Ent.', nameEn: 'JYP Entertainment', market: 'KOSDAQ' },
  { code: '041510', name: '에스엠', nameEn: 'SM Entertainment', market: 'KOSDAQ' },
  { code: '122870', name: '와이지엔터테인먼트', nameEn: 'YG Entertainment', market: 'KOSDAQ' },
  { code: '240810', name: '원익IPS', nameEn: 'Wonik IPS', market: 'KOSDAQ' },
  { code: '067310', name: '하나마이크론', nameEn: 'Hana Micron', market: 'KOSDAQ' },
  { code: '095340', name: 'ISC', nameEn: 'ISC', market: 'KOSDAQ' },
  { code: '214150', name: '클래시스', nameEn: 'Classys', market: 'KOSDAQ' },
]
